"""Add email table

Revision ID: 383e24f77f26
Revises:
Create Date: 2026-02-13 16:37:16.092049

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "383e24f77f26"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable uuid-ossp extension for UUID generation
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table(
        "emails",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "message_id",
            sa.String(length=255),
            nullable=False,
            comment="Provider-specific message ID",
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="Email provider (google, microsoft)",
        ),
        sa.Column(
            "sender",
            sa.String(length=255),
            nullable=False,
            comment="Sender email address",
        ),
        sa.Column(
            "recipient",
            sa.String(length=255),
            nullable=False,
            comment="Primary recipient",
        ),
        sa.Column(
            "recipients_cc", sa.JSON(), nullable=False, comment="CC'd email addresses"
        ),
        sa.Column(
            "recipients_bcc", sa.JSON(), nullable=False, comment="BCC'd email addresses"
        ),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False, comment="Plain text body"),
        sa.Column(
            "body_html", sa.Text(), nullable=True, comment="HTML body if available"
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When email was received",
        ),
        sa.Column(
            "headers", sa.JSON(), nullable=False, comment="Email headers for validation"
        ),
        sa.Column(
            "attachments", sa.JSON(), nullable=False, comment="Attachment metadata"
        ),
        sa.Column(
            "raw_data", sa.JSON(), nullable=False, comment="Original provider data"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "provider", name="uq_message_provider"),
    )
    op.create_index(
        op.f("ix_emails_message_id"), "emails", ["message_id"], unique=False
    )
    op.create_index("ix_emails_received_at", "emails", ["received_at"], unique=False)
    op.create_index(op.f("ix_emails_recipient"), "emails", ["recipient"], unique=False)
    op.create_index("ix_emails_sender", "emails", ["sender"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_emails_sender", table_name="emails")
    op.drop_index(op.f("ix_emails_recipient"), table_name="emails")
    op.drop_index("ix_emails_received_at", table_name="emails")
    op.drop_index(op.f("ix_emails_message_id"), table_name="emails")
    op.drop_table("emails")
    # ### end Alembic commands ###
