"""Add user_email_configuration table

Revision ID: 79796f2a86d2
Revises: a7335bfe2768
Create Date: 2026-02-15 14:33:00.173076

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79796f2a86d2"
down_revision: Union[str, Sequence[str], None] = "a7335bfe2768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_email_configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Reference to user who owns this configuration",
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=False,
            comment="Email provider: 'google' or 'microsoft'",
        ),
        sa.Column(
            "access_token_encrypted",
            sa.Text(),
            nullable=True,
            comment="Encrypted OAuth access token",
        ),
        sa.Column(
            "refresh_token_encrypted",
            sa.Text(),
            nullable=True,
            comment="Encrypted OAuth refresh token",
        ),
        sa.Column(
            "client_id_encrypted",
            sa.Text(),
            nullable=True,
            comment="Encrypted OAuth client ID",
        ),
        sa.Column(
            "client_secret_encrypted",
            sa.Text(),
            nullable=True,
            comment="Encrypted OAuth client secret",
        ),
        sa.Column(
            "provider_config",
            sa.JSON(),
            nullable=False,
            comment="Provider-specific settings: scopes, endpoints, tenant_id, etc.",
        ),
        sa.Column(
            "token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Access token expiration time",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_user_email_config_provider"
        ),
    )
    op.create_index(
        "ix_user_email_configurations_user_id",
        "user_email_configurations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_email_configurations_user_id", table_name="user_email_configurations"
    )
    op.drop_table("user_email_configurations")
    # ### end Alembic commands ###
